FROM python:3.10

WORKDIR /backend
COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt
COPY ./backend/ .
CMD ["python", "-m", "uvicorn", "--host", "0.0.0.0", "--port", "8025", "--access-log", "kulumasiina_backend.api:app"]