version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.front.dev
    ports:
      - "8024:8024"
    environment:
      - VITE_API_PROXY_TARGET=http://api:8025
      - VITE_HOST=0.0.0.0
    volumes:
    - ./frontend:/src/frontend
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api

    env_file:
      - ./.env
    volumes:
      - ./backend:/backend
      - ./db-data:/db-data
