version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - "8024:80"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
      - ./.env
    volumes:
      - ./db-data:/backend/db-data
