version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx.prod
    ports:
      - "127.0.0.1:8024:80"
    restart: always
    # Limit logging to 20MB per container
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    restart: always
    volumes:
      - ./db-data-prod:/db-data/
    env_file: .env
    # Limit logging to 20MB per container
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
