services:
  app:
    image: ghcr.io/fyysikkokilta/kulumasiina-v2:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - '127.0.0.1:8036:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
