FROM node:18 as builder

WORKDIR /src
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm ci

# COPY ./src/ ./public/ tsconfig.json ./
COPY ./frontend/ ./
RUN npm run build

FROM nginx:alpine as server

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /src/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

