version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - "8024:80"
    restart: always
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    restart: always
    volumes:
      - ./db-data:/backend/db-data/
    env_file: .env

# Limit logging to 20MB per container
logging:
  driver: "json-file"
  options:
    max-size: "20m"
