# https://pnpm.io/supply-chain-security
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - next
  - '@next/*'
autoInstallPeers: false
peerDependencyRules:
  ignoreMissing:
    - mssql
    - '@types/mssql'
