allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  compress-pdf: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAge: 1440
overrides:
  ws@<8.21.0: ^8.21.3
  brace-expansion@<5.0.9: ^5.0.9
  fast-uri@<3.1.5: ^3.1.5
  socket.io-parser@<4.2.7: ^4.2.7
  esbuild@>=0.27.3 <0.28.1: ^0.28.2
