allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  compress-pdf: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAge: 1440
patchedDependencies:
  '@tanstack/table-core': 'patches/@tanstack__table-core.patch'
