FROM node:18 as builder

WORKDIR /src
COPY ./package.json ./package-lock.json ./
RUN npm ci

# COPY ./src/ ./public/ tsconfig.json ./
COPY eslint.config.js .prettierrc ./
COPY ./frontend/ ./frontend
RUN npm run build

FROM nginx:alpine as server

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /src/frontend/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

