FROM node:18 as builder

WORKDIR /src
COPY ./package.json ./package-lock.json ./
RUN npm ci

# COPY ./src/ ./public/ tsconfig.json ./
COPY eslint.config.js .prettierrc ./
COPY ./frontend/ ./frontend
#RUN npm run start
CMD ["npm", "run", "start"]

